### ISSUE TITLE
Tagging does not work

### ISSUE THREAD

**Issue by MrNeither** [chuntungho/gist-snippet#1]
Hello. I really like your plugin. Everything works on PyCharm, in addition to combining by tags. I will be very grateful if you show me how to tag it correctly.
![image](https://user-images.githubusercontent.com/42472993/73488046-32e37680-43b9-11ea-9f47-327860279105.png)

**Comment by chuntungho** [comment]
Hi, tag should be wrapped with [], example: [tag1] [tag2] #title# description.
Tag is used for highlighting currently, may support filtering by tag in the future.

**Comment by MrNeither** [comment]
it doesn't work for some reason.
![image](https://user-images.githubusercontent.com/42472993/73664923-4fc9c380-46b1-11ea-9d4e-4ea067e811b9.png)
