### ISSUE TITLE
(Feature request) Auto-view code when gist is clicked

### ISSUE THREAD

**Issue by pedrovhb** [chuntungho/gist-snippet#6]
Hi! Thanks a lot for the plugin, it's great.

One small quality of life improvement I'd like to see is to auto-view the gist file contents when it's the only file in the gist. 

Currently, all gists are listed on the left and to see the code, I have to first double-click the gist name to open the files list, and then click the file to see the code. 

I'd like for the plugin to automatically display code on the right side for the gist when I click the gist itself. This could happen if there's only one file in the gist, or just always show the code for the first file, even if there are multiple ones present.

**Comment by chuntungho** [comment]
Thanks for your great suggestion, it will be implemented in next release.
